### ISSUE TITLE
readResponse taking > 10 seconds, despite given timeout

### ISSUE THREAD

**Issue by vibhavp** [james4k/rcon#1]
From the goroutine dump:

```
goroutine 382 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f3b60d150e0, 0x72, 0x4171c9)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc82025abc0, 0x72, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc82025abc0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc82025ab60, 0xc820538800, 0x100e, 0x100e, 0x0, 0x7f3b60d10050, 0xc82000a130)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc820022368, 0xc820538800, 0x100e, 0x100e, 0x1375a20, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0x121
net.(*TCPConn).Read(0xc820022368, 0xc820538800, 0x100e, 0x100e, 0x0, 0x0, 0x0)
        <autogenerated>:71 +0x7d
github.com/TF2Stadium/Pauling/vendor/github.com/james4k/rcon.(*RemoteConsole).readResponse(0xc820167630, 0x1bf08eb000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/TF2Stadium/Pauling/vendor/github.com/james4k/rcon/rcon.go:163 +0xc0b
github.com/TF2Stadium/Pauling/vendor/github.com/james4k/rcon.(*RemoteConsole).Read(0xc820167630, 0x0, 0x0, 0xb475, 0x0, 0x0)
        /home/travis/gopath/src/github.com/TF2Stadium/Pauling/vendor/github.com/james4k/rcon/rcon.go:98 +0x75

```

This is despite `Read()` calling readResponse with a given timeout of 2 minutes
Could it be that SetReadDeadline needs to be called before every read?

**Comment by james4k** [comment]
SetReadDeadline is called just before the Read in the callstack you show there, so don't think that is the issue here.

Does it ever timeout?

**Comment by vibhavp** [comment]
The goroutine stays there for ~4 minutes, after which is exits, presumably due to the timeout, but shouldn't it exit after 2 minutes?

**Comment by james4k** [comment]
Are you going purely by the callstack info, or is this timed?

How did you originally encounter this issue?

**Comment by vibhavp** [comment]
Hm, looks like a function earlier in the callstack for responsible for this. Sorry about that
